/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Advisers;
import model.Prioritys;
import model.Punts;
import model.PuntsServices;
import model.Service;
import model.ServiceTailM;
import model.TailattenTionM;
import model.Turns;

/**
 *
 * @author ANDRES
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnServicio = new javax.swing.JButton();
        btnPrioridad = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPunto = new javax.swing.JButton();
        btnTurn = new javax.swing.JButton();
        btnAdviser = new javax.swing.JButton();
        btnAtention = new javax.swing.JButton();
        btnListS = new javax.swing.JButton();
        btnListA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(400, 400));

        btnServicio.setText("Servicios");
        btnServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicioActionPerformed(evt);
            }
        });

        btnPrioridad.setText("Priroridad");
        btnPrioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrioridadActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fiscalias-de-turno.png"))); // NOI18N

        btnPunto.setText("Punto At.");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        btnTurn.setText("Turno");
        btnTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnActionPerformed(evt);
            }
        });

        btnAdviser.setText("Prestador");
        btnAdviser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdviserActionPerformed(evt);
            }
        });

        btnAtention.setText("Atender");
        btnAtention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtentionActionPerformed(evt);
            }
        });

        btnListS.setText("Lista servicio");
        btnListS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListSActionPerformed(evt);
            }
        });

        btnListA.setText("Lista atención");
        btnListA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdviser, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(btnServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrioridad, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPunto, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(btnTurn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAtention, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnListA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnServicio)
                    .addComponent(btnPunto)
                    .addComponent(btnListS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrioridad)
                    .addComponent(btnTurn)
                    .addComponent(btnListA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdviser)
                    .addComponent(btnAtention))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicioActionPerformed
        // TODO add your handling code here:
        ServiceView serviceview = new ServiceView();
        Service service = new Service();
        serviceview.setTitle("Lista de servicios");
        serviceview.setLocationRelativeTo(this);
        serviceview.setVisible(true);
        service.LlenarServicio(serviceview.tblService, "");
    }//GEN-LAST:event_btnServicioActionPerformed

    private void btnPrioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrioridadActionPerformed
        // TODO add your handling code here:
        PriorityView prioritysview = new PriorityView();
        Prioritys prioritys = new Prioritys();
        prioritysview.setTitle("Lista de prioridades");
        prioritysview.setLocationRelativeTo(this);
        prioritysview.setVisible(true);
        prioritys.LlenarPriority(prioritysview.tblService, "");
    }//GEN-LAST:event_btnPrioridadActionPerformed

    private void btnAdviserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdviserActionPerformed
        // TODO add your handling code here:
        AdviserView adviserview = new AdviserView();
        Advisers advisers = new Advisers();
        adviserview.setTitle("Lista de prioridades");
        adviserview.setLocationRelativeTo(this);
        adviserview.setVisible(true);
        advisers.LlenarAdviser(adviserview.tblService, "");
    }//GEN-LAST:event_btnAdviserActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        // TODO add your handling code here:
        PuntoView puntoview = new PuntoView();
        Punts punts = new Punts();
        PuntsServices puntsService = new PuntsServices();
        puntoview.setTitle("Configuración punto de atención");
        puntoview.setLocationRelativeTo(this);
        puntoview.setVisible(true);
        punts.LlenarPunto(puntoview.tblPunto, "");
        puntsService.LlenarPuntoservices(puntoview.tblServices, "");
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnActionPerformed
        // TODO add your handling code here:
        TurnsView turnsview = new TurnsView();
        Turns turns = new Turns();
        turnsview.setTitle("Solicitud turno de atección");
        turnsview.setLocationRelativeTo(this);
        turnsview.setVisible(true);
    }//GEN-LAST:event_btnTurnActionPerformed

    private void btnAtentionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtentionActionPerformed
        // TODO add your handling code here:
        AtenderView atenderview = new AtenderView();
        atenderview.setTitle("Atención de usuarios");
        atenderview.setLocationRelativeTo(this);
        atenderview.setVisible(true);
    }//GEN-LAST:event_btnAtentionActionPerformed

    private void btnListSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListSActionPerformed
        // TODO add your handling code here:
        ListView listview = new ListView();
        ServiceTailM servicetailm = new ServiceTailM();
        listview.setTitle("Lista de servicios disponibles para antender");
        listview.setLocationRelativeTo(this);
        listview.setVisible(true);
        servicetailm.LlenarTailm(listview.tblList, "");
    }//GEN-LAST:event_btnListSActionPerformed

    private void btnListAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListAActionPerformed
        // TODO add your handling code here:
        ListView listview = new ListView();
        TailattenTionM tailattenionm = new TailattenTionM();
        listview.setTitle("Lista de usuarios antendendidos");
        listview.setLocationRelativeTo(this);
        listview.setVisible(true);
        tailattenionm.LlenarAttention(listview.tblList, "");


    }//GEN-LAST:event_btnListAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdviser;
    private javax.swing.JButton btnAtention;
    private javax.swing.JButton btnListA;
    private javax.swing.JButton btnListS;
    private javax.swing.JButton btnPrioridad;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnServicio;
    private javax.swing.JButton btnTurn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
